apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-nginx-aks-app1
  name: custom-nginx-aks-app1
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: custom-nginx-aks-app1
  template:
    metadata:
      labels:
        app: custom-nginx-aks-app1