apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-nginx-aks-app1
  name: custom-nginx-aks-app1
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: custom-nginx-aks-app1
  ports:
    - port: 80
      targetPort: 80